verbose: True # Whether to print info.
log_full_detail: False # if True, logs a more detailed information to tensorboard.

# ========== HYPERPARAMTERS DDPG: ============= 
mode: "train" # ['train', 'test'] # TODO: set from config
total_episodes: 100 # total number of episodes to train
max_episode_length: 200 # maximum iteration length of an episode.
warmup_steps: 100 # number of steps to take random actions before using the agents policy
update_every: 200 # update model after every update_every steps taken.
num_updates: 100 # at every update_every steps while updating the model perform num_updates many updates by sampling a new batch for each of them. 
actor_hidden_dims: [400, 300] # holds dimensions of the hidden layers excluding the input layer and the input and the output dimensions for the actor network of ddpg agent.
critic_hidden_dims: [400, 300] # holds dimensions of the hidden layers excluding the input layer and the input and the output dimensions for the critic network of ddpg agent.
actor_lr: 1e-3 # learning rate for the Actor Network20
critic_lr: 1e-3 # learning rate for the Critic Network
initial_epsilon: 1.0 # epsilon used for multiplying the gaussian distribution sample to obtain the noise to add to the agent's action (exploration).
epsilon_decay: 0.999 # every time an action is taken epsilon is reduced by this amount (i.e. epsilon *= epsilon_decay).
min_epsilon: 0.05 # minimum value that epsilon can decay to
act_noise: 0.1 # stddev for Gaussian exploration noise added to policy at training time. (At test time, no noise is added.)
target_noise: 0.2 # stddev for smoothing noise added to target policy.
clip_noise_range: 0.0 #0.5 # noise is clipped btw [-clip_noise_range, clip_noise_range] before being added to the action
gamma: 0.9999 # next state discount rate
tau: 0.995 # tau value used in updating the target networks using polyak averaging (i.e. targ_net = tau*targ_net + (1-tau) * net).
policy_update_delay: 1 # Actor is updated after every policy_update_delay number of updates
replay_buffer_size: 1_000_000 # size of the replay buffer
batch_size: 100
seed: 42 # used to set seed for reproducibility
save_every: 5000 # specifies after every how many updates to the model the agent model is saved. Model is saved at the end of 'total_episodes' episode.
# ======================================= 